spring:
  application:
    name: techstockmaster_api

  datasource:
    local:
      url: jdbc:mysql://localhost:3306/bd_estoque?allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: 616853
    lykos:
      url: jdbc:mysql://${LYKOSHOST}:${LYKOSPORT}/${LYKOSDATABASE}?allowPublicKeyRetrieval=true&useSSL=false
      username: ${LYKOSUSER}
      password: ${LYKOSPASSWORD}

  doc:
    swagger-ui:
      path: /doc.html

security:
  config:
    prefix: Bearer
    key: SECRET_KEY
    expiration: 3600000
