spring:
  application:
    name: techstockmaster_api

  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}

    url_Lykos: jdbc:mysql://${LYKOSHOST}:${LYKOSPORT}/${LYKOSDATABASE}?allowPublicKeyRetrieval=true&useSSL=false
    username_Lykos: ${LYKOSUSER}
    password_Lykos: ${LYKOSPASSWORD}
    update: tre

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

security:
  config:
    prefix: Bearer
    key: SECRET_KEY
    expiration: 3600000
